package si.modrajagoda.didi.database;

import java.sql.SQLException;

import si.modrajagoda.didi.R;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;

import com.j256.ormlite.android.apptools.OrmLiteSqliteOpenHelper;
import com.j256.ormlite.dao.Dao;
import com.j256.ormlite.support.ConnectionSource;

public class DatabaseHelper extends OrmLiteSqliteOpenHelper {
	
	private static final String DATABASE_NAME = "habits.db";
	private static final int DATABASE_VERSION = 1;
	
	// the DAO object used to access the tables
	private Dao<Habit, Integer> habitDao;

	//DatabaseHelper includes config file that was generated by DatabaseConfigUtil 
	public DatabaseHelper(Context context) {
		super(context, DATABASE_NAME, null, DATABASE_VERSION, R.raw.ormlite_config); 
	}

	@Override
	public void onCreate(SQLiteDatabase sqliteDatabase, ConnectionSource connectionSource) {
		// No need to create tables (will be done manually)
	}

	@Override
	public void onUpgrade(SQLiteDatabase sqliteDatabase, ConnectionSource connectionSource, int oldVer, int newVer) {
		// Not needed
	}
	
	/**
	 * Returns the Database Access Object (DAO) for table class. It will create it or just give the cached
	 * value.
	 */
	public Dao<Habit, Integer> getHabitDao() throws SQLException {
		if (habitDao == null) {
			habitDao = getDao(Habit.class);
		}
		return habitDao;
	}
	
	/**
	 * Close the database connections and clear any cached DAOs.
	 */
	@Override
	public void close() {
		super.close();
		habitDao = null;
	}
}
